FROM node:9-alpine

WORKDIR /usr/src/app

#install dependencies
COPY package.json .

RUN npm install --quiet && \
    npm cache clean --force

#isntall nodemon for development mode
RUN npm install nodemon -g --quiet

COPY . .

EXPOSE 3000

CMD npm run dev
#CMD ["node", "src/index.js"]